scala_sources(
  dependencies=[
    # TODO: Package objects exposed with improper nesting: https://github.com/pantsbuild/pants/issues/13753.
    "akka-http/src/main/scala/akka/http/scaladsl/marshalling/package.scala",
  ],
)
