scalatest_tests(
  dependencies=[
    # TODO: Is [overlapped with thirdparty](https://github.com/pantsbuild/pants/issues/13661).
    "akka-http-core/src/test/scala/akka/testkit/AkkaSpec.scala",
  ],
)
