scala_sources(
  dependencies=[
    # TODO: Scala import of Java method not inferred: https://github.com/pantsbuild/pants/issues/13750.
    "akka-http/src/main/java/akka/http/javadsl/common/RegexConverters.java",
  ],
)
