scala_sources(
  dependencies=[
    # TODO: Imports from empty package. See https://github.com/pantsbuild/pants/issues/13742.
    "akka-http-core/src/main/scala-2.13+/akka/http/ccompat/imm/package.scala",
  ],
)
