java_sources(
  dependencies=[
    # TODO: Used as fully qualified: https://github.com/pantsbuild/pants/issues/13741.
    "akka-http-core/src/main/scala/akka/http/scaladsl/model/sse/ServerSentEvent.scala",
  ],
)
