scala_junit_tests()

scala_sources(
    name="ws0",
    dependencies=[
      # TODO: Is [overlapped with thirdparty](https://github.com/pantsbuild/pants/issues/13661).
      "akka-http-core/src/test/scala/akka/stream/testkit/Utils.scala",
    ],
)
