java_sources(
  dependencies=[
    # TODO: Import of inner enum: https://github.com/pantsbuild/pants/issues/13745
    "akka-http-core/src/main/java/akka/http/shaded/com/twitter/hpack/HpackUtil.java",
    # TODO: static-final return type: https://github.com/pantsbuild/pants/issues/13746
    "akka-http-core/src/main/java/akka/http/shaded/com/twitter/hpack/HuffmanDecoder.java",
    "akka-http-core/src/main/java/akka/http/shaded/com/twitter/hpack/HuffmanEncoder.java",
  ],
)
