scala_sources(
  dependencies=[
    # TODO: Used as relative import: https://github.com/pantsbuild/pants/issues/13740.
    "akka-http/src/main/scala/akka/http/scaladsl/common/EntityStreamingSupport.scala",
  ],
)
