scala_sources(
  dependencies=[
    # TODO: Used as a relative import: https://github.com/pantsbuild/pants/issues/13740.
    "akka-http-core/src/main/java/akka/http/javadsl/model/ContentRange.java",
  ],
)
