scala_sources(
  dependencies=[
    # TODO: Is [overlapped with thirdparty](https://github.com/pantsbuild/pants/issues/13661).
    "akka-http-tests/src/multi-jvm/scala/akka/testkit/TestTags.scala",
  ],
)
