scala_sources(
  dependencies=[
    # TODO: Used as annotation: https://github.com/pantsbuild/pants/issues/13751.
    "akka-http/src/main/java/akka/http/javadsl/server/directives/CorrespondsTo.java",
  ],
)
