scala_sources(
  dependencies=[
    # TODO: Nested package import: https://github.com/pantsbuild/pants/issues/13655.
    "akka-http/src/main/scala/akka/http/javadsl/server/directives/FormFieldDirectives.scala",
  ],
)
